server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /auth-remote/ {
        resolver 127.0.0.11 ipv6=off valid=30s;
        set $auth_service auth;
        proxy_pass http://$auth_service:80;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /management-remote/ {
        resolver 127.0.0.11 ipv6=off valid=30s;
        set $management_service management;
        proxy_pass http://$management_service:80;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
